# Generated by Django 5.1 on 2024-08-31 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson',
            new_name='course',
        ),
    ]
